version: '2'

services:
  web:
    build: .
    ports:
      - 8040:8040
    volumes:
      - /home/zec/chess_board_21Dec/chessboard_folder:/app
    command: python3 manage.py runserver 0.0.0.0:8040


    

